# Optimized Docker Compose Configuration for BucketLab API
# Addresses security, performance, and reliability issues

services:
  # Cloudflare Tunnel Service
  cloudflared:
    env_file: ".env"
    container_name: cloudflared
    hostname: bucketlab-API-tunnel_dev
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    # FIXED: Use bridge network instead of host for better isolation
    networks:
      - bucketLab_internal
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    # ADDED: Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M

  # App Server (API Gateway)
  app_server:
    container_name: app_server
    image: node:22.14.0
    environment:
      # FIXED: Added authSource parameter for MongoDB authentication
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017/?authSource=admin"
      - NODE_ENV=${APP_RUN_MODE:-prod}
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "4020:4020"  # Only expose the main API port
    command: sh -c "npm ci --only=production && npm run start:${APP_RUN_MODE:-prod}"
    depends_on:
      mongoDB:
        condition: service_healthy
    networks:
      - bucketLab_internal
    restart: unless-stopped
    # ADDED: Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # ADDED: Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M

  # Auth Server (Internal Service)
  auth_server:
    container_name: auth_server
    image: node:22.14.0
    environment:
      # FIXED: Added authSource parameter
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017/?authSource=admin"
      - NODE_ENV=${APP_RUN_MODE:-prod}
    working_dir: /auth
    volumes:
      - ./auth:/auth
    # REMOVED: External port exposure for security
    expose:
      - "4021"
    command: sh -c "npm ci --only=production && npm run start:${APP_RUN_MODE:-prod}"
    depends_on:
      mongoDB:
        condition: service_healthy
    networks:
      - bucketLab_internal
    restart: unless-stopped
    # ADDED: Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4021/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # ADDED: Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M

  # Laboratory Server (Internal Service)
  laboratory_server:
    container_name: laboratory_server
    image: node:22.14.0
    environment:
      # FIXED: Added authSource parameter
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017/?authSource=admin"
      - NODE_ENV=${APP_RUN_MODE:-prod}
    working_dir: /laboratory
    volumes:
      - ./laboratory:/laboratory
    # REMOVED: External port exposure for security
    expose:
      - "4420"
    command: sh -c "npm ci --only=production && npm run start:${APP_RUN_MODE:-prod}"
    depends_on:
      mongoDB:
        condition: service_healthy
    networks:
      - bucketLab_internal
    restart: unless-stopped
    # ADDED: Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4420/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # ADDED: Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M

  # MongoDB Database
  mongoDB:
    container_name: bucketlab_empire_database
    image: mongo:7.0  # CHANGED: Use specific version instead of 'latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
      # ADDED: Additional MongoDB configuration
      MONGO_INITDB_DATABASE: "bucketlab"
    # REMOVED: External port exposure for security
    expose:
      - "27017"
    volumes:
      # IMPROVED: Use named volume for better performance
      - mongodb_data:/data/db
      # ADDED: MongoDB configuration
      - ./mongodb/mongod.conf:/etc/mongod.conf:ro
    networks:
      - bucketLab_internal
    restart: unless-stopped
    # IMPROVED: Better health check
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # ADDED: Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M

# ADDED: Named volumes for better performance
volumes:
  mongodb_data:
    driver: local

networks:
  bucketLab_internal:
    name: bucketLab_internal
    driver: bridge
    # ADDED: Network configuration for better isolation
    ipam:
      config:
        - subnet: 172.20.0.0/16
