services:
  app:
    # Load environment variables from .env file.
    # This to applies to the app service, which makes sense.
    # But it also seems to applu to the mongoDB service as well, though I'm not sure why/how...
    env_file: ".env"
    container_name: server
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 4020:4020
    environment:
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017"
    command: npm run start:dev
    depends_on:
      - mongoDB
  mongoDB:
    container_name: database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
volumes:
  data:
    driver: local