services:
  cloudflared:
    env_file: ".env"
    container_name: cloudflared
    hostname: bucketlab-API-tunnel_dev
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    network_mode: host  # Reverted: Required for Cloudflare tunnel to access host services
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
  app_server:
    container_name: app_server
    image: node:22.14.0
    environment:
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017/?authSource=admin"
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 4020:4020
    command: "npm run start:${APP_RUN_MODE}"
    depends_on:
      mongoDB:
        condition: service_healthy
    networks:
      - bucketLab_internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  auth_server:
    container_name: auth_server
    image: node:22.14.0
    environment:
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017/?authSource=admin"
    working_dir: /auth
    volumes:
      - ./auth:/auth
    expose:
      - "4021"  # Changed from ports to expose for internal access only
    command: "npm run start:${APP_RUN_MODE}"
    depends_on:
      mongoDB:
        condition: service_healthy
    networks:
      - bucketLab_internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  laboratory_server:
    container_name: laboratory_server
    image: node:22.14.0
    environment:
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017/?authSource=admin"
    working_dir: /laboratory
    volumes:
      - ./laboratory:/laboratory
    expose:
      - "4420"  # Changed from ports to expose for internal access only
    command: "npm run start:${APP_RUN_MODE}"
    depends_on:
      mongoDB:
        condition: service_healthy
    networks:
      - bucketLab_internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  mongoDB:
    container_name: bucketlab_empire_database
    image: mongo:7.0  # Changed from 'latest' to specific version
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
    expose:
      - "27017"  # Changed from ports to expose for internal access only
    volumes:
      - mongodb_data:/data/db  # Changed to named volume for better performance
    networks:
      - bucketLab_internal
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --port 27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
volumes:
  mongodb_data:
    driver: local

networks:
  bucketLab_internal:
    name: bucketLab_internal
    driver: bridge