services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 4020:4020
    environment:
      - MONGO_URI=mongodb://admin:password@mongoDB:27017
    command: npm run start:prod
    depends_on:
      - mongoDB
  mongoDB:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: docker run --no-autoupdate
    environment:
      - TUNNEL_TOKEN: eyJhIjoiMDM3ZmQ5YzczMzQyMmQxMmEwMTk0NWQwZTQ4ZjQ0NjQiLCJ0IjoiYTMyODA1NWEtY2ViNS00YThiLTlkYTUtMjNhYmNkNzc5YTNjIiwicyI6Ill6TTVZelV5Wm1VdE56ZG1ZaTAwTW1VNUxXSTVPVEV0TnpRMFltWTJZMkl6WXpRNCJ9
    ports:
      - 4020:4020
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./cloudflared:/etc/cloudflared
volumes:
  data:
    driver: local