services:
  cloudflared:
    env_file: ".env"
    container_name: cloudflared
    hostname: bucketlab-API-tunnel_dev
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro   # Synchronize time with the host
  app_server:
    env_file: "./app/app.env"
    environment:
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017"
    container_name: app_server
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 4020:4020
    command: "npm run start:${APP_RUN_MODE}"
    depends_on:
      - mongoDB
    links:
      - laboratory_server
      - auth_server
    networks:
      - bucketLab_internal
  laboratory_server:
    env_file: "./laboratory/laboratory.env"
    environment:
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017"
    container_name: laboratory_server
    image: node:latest
    working_dir: /laboratory
    volumes:
      - ./laboratory:/laboratory
    ports:
      - 4420:4420
    command: "npm run start:${APP_RUN_MODE}"
    depends_on:
      - mongoDB
    networks:
      - bucketLab_internal
  auth_server:
    env_file: "./auth/auth.env"
    environment:
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017"
    container_name: auth_server
    image: node:latest
    working_dir: /auth
    volumes:
      - ./auth:/auth
    ports:
      - 4021:4021
    command: "npm run start:${APP_RUN_MODE}"
    depends_on:
      - mongoDB
    networks:
      - bucketLab_internal

  mongoDB:
    container_name: bucketlab_empire_database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - bucketLab_internal
volumes:
  data:
    driver: local
networks:
  bucketLab_internal:
    name: bucketLab_internal
    driver: bridge