services:
  cloudflared:
    container_name: cloudflared
    hostname: bucketlab-API-tunnel_dev
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    volumes:
      - /etc/localtime:/etc/localtime:ro   # Synchronize time with the host
  app:
    env_file: ".env"
    container_name: server
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 4020:4020
    environment:
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017"
    command: "npm run start:${APP_RUN_MODE}"
    depends_on:
      - mongoDB
    networks:
      - internal
  mongoDB:
    container_name: database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - internal
volumes:
  data:
    driver: local
networks:
  internal:
    name: internal
    driver: bridge