services:
  cloudflared:
    container_name: cloudflared
    hostname: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    # Volume configuration for time synchronization and hosts file persistence
    volumes:
      - /etc/localtime:/etc/localtime:ro   # Synchronize time with the host
  app:
    # Load environment variables from .env file.
    # This to applies to the app service, which makes sense.
    # But it also seems to apply to the mongoDB service as well, though I'm not sure why/how...
    env_file: ".env"
    container_name: server
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 4020:4020
    environment:
      - "MONGO_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongoDB:27017"
    command: "${APP_START_CMD}"
    depends_on:
      - mongoDB
    networks:
      - internal
  mongoDB:
    container_name: database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - internal
volumes:
  data:
    driver: local
networks:
  internal:
    name: internal
    driver: bridge
# This docker-compose file sets up a simple web application with a MongoDB database and a Cloudflare tunnel.
# The app service runs a Node.js application, the mongoDB service runs a MongoDB database,
# and the cloudflared service creates a secure tunnel to the Cloudflare network.
# The app service depends on the mongoDB service, and the cloudflared service is connected to an external network.
# The environment variables are loaded from a .env file, and the MongoDB credentials are passed to the app service.
# The data for the MongoDB database is stored in a local volume.
# The cloudflared service exposes port 4200, the app service exposes port 4020, and the mongoDB service exposes port 27017.
# Make sure to set the TUNNEL_TOKEN, MONGO_DB_USERNAME, and MONGO_DB_PASSWORD in your .env file.
# Note: Ensure that the .env file is in the same directory as this docker-compose file.